# options (https://github.com/JohnnyMorganz/StyLua#options)
indent-type = "Spaces" # prefer spaces as indent type
indent-width = 2 # use 2 characters as indent
quote-style = "AutoPreferSingle" # prefer single quote style
column-width = 120 # (also relevant for `collapse-simple-statement`)
call-parentheses = "None" # omits parentheses on single string or table
collapse-simple-statement = "Always" # always collapse simple statements
